### ISSUE TITLE
Compilation error on ubuntu focal fossa

### ISSUE THREAD

**Issue by sportegioco** [mugiseyebrows/mugi-grep#15]
Compilation error on ubuntu focal fossa:

administrator@natale14:~/mugi-grep-1.5.0$ make
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DHAS_PLACEHOLDER_TEXT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Isrc -Isrc/widget -Isrc/model -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o searchoptionswidget.o src/widget/searchoptionswidget.cpp
In file included from src/widget/searchoptionswidget.cpp:2:
src/widget/ui_searchoptionswidget.h:20:10: fatal error: src\widget\lineeditandcheckbox.h: File o directory non esistente
   20 | #include "src\widget\lineeditandcheckbox.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1424: searchoptionswidget.o] Errore 1

**Comment by mugiseyebrows** [comment]
fixed in a6457e1d9c32a707d72685916b585cca83a5260b thank you
