### ISSUE TITLE
Doesn't work, useless

### ISSUE THREAD

**Issue by garry-ut99** [mugiseyebrows/mugi-grep#17]
(Win 7 SP1 64.) The tool GUI opens, but after pressing "search" or "replace buttons" to find some text in some files, nothing happens, no reaction...

**Comment by mugiseyebrows** [comment]
@garry-ut99 you need to select path first

**Comment by garry-ut99** [comment]
Good joke, but I DID select the f...ing path. This is not where the problem is. The tool doesn't work with files bigger than lets say 100mb, no reaction after pressing search button. I discovered it by decerasing size of the txt file from 700mb to 350mb then to 175mb, finally to something like 70mb, and finally it has started to work, not to mention it's terribly slow with a 70mb file. It's definately designed for small files only. No, it's not me who "need to select path first" , it's you who needs to fix your program, unless it's designed only for small files and you don't care, but still there should be some error message saying about too big file, instead of silently skipping it without any notification, as this is a terrible coding practice, unless there is a dirty bug causing search to not work with bigger files.

**Comment by mugiseyebrows** [comment]
@garry-ut99 a tip for you: if you want something done be nice, I dont owe you anything buddy, go grep your logs with something else.

**Comment by garry-ut99** [comment]
> mugiseyebrows : a tip for you (...)

A tip for you: don't proivde foolish replies.

> mugiseyebrows : be nice

Don't cry, I'm aint your girlfriend or pet to be nice at your call, you aint my mom / dad, I decide to who and when I am nice.

> mugiseyebrows : if you want something done (...)

Maybe in your dreams, nowhere did I say I wanted anything to be done from you, nor that I need your tool in my life, I was just simply testing several tools of such kind and I just simply thought that it would be NICE to report a bug so that you are at least aware, and I don't care whether you fix your bugs or not, you seem to be another developer with an oversized ego who thinks that everyone who reports a bug is immediately asking for it to be fixed. I don't need it to be fixed because there is plenty of similiar tools, and I will just "go grep my logs with something else" - yes that's exactly what I'm going to do, hence I don't know why ever did you think I wanted anything from you, it must be your imagination. I just simply ping-ponged your "you need" reply and described the bug technically.
